"use client";
import {useState} from 'react';
const sources=[
 {name:'Verdun et environs',area:'Meuse · France',url:'https://www.meteoblue.com/en/weather/webcams/verdun_france_2969958',note:'Sommedieue / aéroport du Rozelier à environ 8 km. Images actualisées ; vérifier leur horodatage. Aucun flux du centre de Verdun confirmé.'},
 {name:'Grandes villes du monde',area:'SkylineWebcams',url:'https://www.skylinewebcams.com/en/live-cams-category/city-cams.html',note:'Annuaire de caméras urbaines publiques : choisissez la ville chez le diffuseur. Disponibilité variable.'},
 {name:'Carte mondiale des webcams',area:'EarthCam',url:'https://www.earthcam.com/mapsearch/',note:'Carte interactive mondiale. Recherchez une ville ou explorez les caméras publiques.'},
 {name:'Réseau mondial EarthCam',area:'Tous continents',url:'https://www.earthcam.com/network/?lang=en&us=',note:'Sélection de destinations et lecteurs officiels du réseau.'}
];
export default function CityCameras(){const [query,setQuery]=useState('');const filtered=sources.filter(s=>(s.name+' '+s.area+' '+s.note).toLowerCase().includes(query.toLowerCase()));return <section className="min-h-0 flex-1 overflow-auto p-4"><h2 className="mb-3 text-xl text-cyan-100">Fenêtres sur le monde</h2><p className="mb-5 max-w-3xl text-sm text-slate-300">Webcams publiques de Verdun et accès aux grandes villes du monde. Les lecteurs s’ouvrent sur le site du diffuseur. Ce répertoire ne garantit pas une caméra dans chaque ville, ni une diffusion permanente.</p><label className="block text-sm">Filtrer les sources<input aria-label="Filtrer les sources de webcams" className="my-2 block w-full rounded border border-cyan-900 bg-slate-950 p-3" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Verdun, monde, EarthCam…"/></label><div className="grid gap-4 md:grid-cols-2">{filtered.map(s=><article key={s.url} className="rounded-xl border border-cyan-800/50 bg-slate-950/70 p-5"><span className="text-xs uppercase tracking-widest text-cyan-400">{s.area}</span><h3 className="my-3 text-lg">{s.name}</h3><p className="mb-5 text-sm leading-6 text-slate-300">{s.note}</p><a className="hud-btn inline-flex" href={s.url} target="_blank" rel="noopener noreferrer">Ouvrir les webcams ↗</a><p className="mt-3 text-xs text-slate-500">État du flux non vérifié automatiquement · source publique</p></article>)}</div>{!filtered.length&&<p className="p-5">Aucune source correspondante. Ouvrez la carte mondiale pour rechercher une autre ville.</p>}<p className="mt-5 text-xs text-slate-400">Une mention « direct » chez le diffuseur n’exclut pas un délai de transmission. Vérifiez la date affichée sur l’image. Aucun accès aux caméras privées ou municipales non publiques.</p></section>}
